### ISSUE TITLE
super() argument 1 must be type, not classobj

### ISSUE THREAD

**Issue by azureskies** [shijl0925/python-sonarqube-api#12]
在macOS環境下python 2.7 / 3.8 會無法執行

Traceback (most recent call last):
  File "/Users/xxx/xxx/test.py", line 26, in <module>
    getSonarqubeInfo()
  File "/Users/xxx/xxx/test.py", line 5, in getSonarqubeInfo
    sonar.auth.authenticate_user(login=username, username=username, password=password)
  File "/Users/xxx/xxx/venv/lib/python2.7/site-packages/sonarqube/community/__init__.py", line 229, in auth
    return SonarQubeAuth(api=self)
  File "/Users/xxx/xxx/venv/lib/python2.7/site-packages/sonarqube/community/auth.py", line 23, in __init__
    super(SonarQubeAuth, self).__init__(**kwargs)
TypeError: super() argument 1 must be type, not classo

**Comment by shijl0925** [comment]
I have fixed this bug now, please the latest package( >= 1.1.8) .
