### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getfullargspec'

### ISSUE THREAD

**Issue by suresh4test** [shijl0925/python-sonarqube-api#29]
I am using python 2.7 virutlenv and getting below error messages.I cloned repo and done setup.
I am getting same kind of error with any api call.

>>> result = sonar.auth.check_credentials()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sonarqube/utils/common.py", line 116, in inner_func
    func_params = translate_params(f, *args, **kwargs)
  File "sonarqube/utils/common.py", line 59, in translate_params
    all_params = dict(get_default_kwargs(f))
  File "sonarqube/utils/common.py", line 43, in get_default_kwargs
    argspec = inspect.getfullargspec(func)
AttributeError: 'module' object has no attribute 'getfullargspec'

**Comment by shijl0925** [comment]
I have fixed it, please update your package.
