### ISSUE TITLE
get_rule() is broken for SonarCloud

### ISSUE THREAD

**Issue by damiencarol** [shijl0925/python-sonarqube-api#36]
This snippet:
```
from sonarqube import SonarCloudClient

token = "..."
sonar = SonarCloudClient(sonarcloud_url="https://sonarcloud.io", token=token)
issues = sonar.issues.search_issues(componentKeys="...")
for issue in issues:
    print(f"key: {issue['key']}")
    print(f"rule: {sonar.rules.get_rule(issue['rule'])}")
```
Generate:
```
key: AXxbH--R-dDKUnsQv6k7
Traceback (most recent call last):
  File "/home/damien/python-sonarqube-api/test_cloud.py", line 8, in <module>
    print(f"rule: {sonar.rules.get_rule(issue['rule'])}")
  File "/home/damien/python-sonarqube-api/sonarqube/utils/common.py", line 132, in inner_func
    response = self._get(url_pattern, params=params)
  File "/home/damien/python-sonarqube-api/sonarqube/utils/rest_client.py", line 144, in _get
    return self.request("GET", path=path, params=params, data=data, headers=headers)
  File "/home/damien/python-sonarqube-api/sonarqube/utils/rest_client.py", line 82, in request
    raise ValidationError(msg)
sonarqube.utils.exceptions.ValidationError: Error in request. Possibly validation error [400]: The 'organization' parameter is missing
```

**Comment by damiencarol** [comment]
ok. thanks.
