### ISSUE TITLE
Validation failure for summaryCommentEnabled when configuring GitHub ALM from 1.2.6 onwards

### ISSUE THREAD

**Issue by zoonage** [shijl0925/python-sonarqube-api#48]
Relevant line of code: 

```
sonar.alm_settings.set_github_binding(almSetting="github", project=project_name, repository=github_repo, summaryContentEnabled=True)
```

Gives the following exception from 1.2.6 onwards

```
Traceback (most recent call last):
  File "./scripts/sonarqube-project-setup.py", line 45, in <module>
    sonar.alm_settings.set_github_binding(almSetting="github", project=project_name, repository=github_repo, summaryContentEnabled=True)
  File "/usr/local/lib/python3.7/site-packages/sonarqube/utils/common.py", line 134, in inner_func
    response = self._post(url_pattern, params=params)
  File "/usr/local/lib/python3.7/site-packages/sonarqube/utils/rest_client.py", line 165, in _post
    params=params,
  File "/usr/local/lib/python3.7/site-packages/sonarqube/utils/rest_client.py", line 82, in request
    raise ValidationError(msg)
sonarqube.utils.exceptions.ValidationError: Error in request. Possibly validation error [400]: Property summaryCommentEnabled is not a boolean value: True
```

**Comment by stastnypremysl** [comment]
Solution: https://github.com/shijl0925/python-sonarqube-api/pull/47

**Comment by shijl0925** [comment]
please update the package version 1.2.9
