### ISSUE TITLE
403 with project search

### ISSUE THREAD

**Issue by alexcfpho** [shijl0925/python-sonarqube-api#9]
Hey there:
@shijl0925 
I've been trying to figure out if this is something silly that I'm getting wrong on my end, or is a legitimate bug with the `projects.search_projects()` endpoint.

I've confirmed that my token isn't related to the 403 error I've been getting via a curl to the underlying project search endpoint directly and get a `200` with the expected response. I've used the same token with a few other methods to test and no issues.

Quickly testing out the endpoint here as such:
```python
   output = list(sq_obj.projects.search_projects())
   print(output)
```

Here's the stack trace I get when I try to call the method:

```python
Traceback (most recent call last):
  File "/Users/apho/Documents/Dev/xwing/automation-pipelines/sonarqube-config-pipeline/permissions.py", line 186, in <module>
    print(sq_obj.projects.get("access-api-dev"))
  File "/usr/local/lib/python3.8/site-packages/sonarqube/community/projects.py", line 33, in get
    result = list(self.search_projects(projects=key))
  File "/usr/local/lib/python3.8/site-packages/sonarqube/utils/common.py", line 160, in inner_func
    response = self._get(url_pattern, params=params).json()
  File "/usr/local/lib/python3.8/site-packages/sonarqube/utils/rest_client.py", line 113, in _get
    return self.request('GET', path=path, params=params, data=data, headers=headers)
  File "/usr/local/lib/python3.8/site-packages/sonarqube/utils/rest_client.py", line 73, in request
    raise AuthError(msg)
sonarqube.utils.exceptions.AuthError: Error in request. Possibly authentication failed [403]: Forbidden
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

Any ideas?

**Comment by srsouto** [comment]
The issue appears to be when you specify `onProvisionedOnly` as a parameter to the GET. I tried visiting `{sonarqube}/api/projects/search?onProvisionedOnly=false` and receive a 403.
